version: '3'
services:
  pulsar:
    image: apachepulsar/pulsar:latest@sha256:bc40b0d47b7ba2e5de85c4d95a5b5acbd6f1a7c0865d4306a7f3f87fa75a8fbc
    container_name: pulsar
    ports:
      - 6650:6650  # Pulsar broker port
      - 8080:8080  # Pulsar admin web UI
    command: bin/pulsar standalone
