version: '3'
services:
  pulsar:
    image: apachepulsar/pulsar:latest@sha256:db2b860009fc22b9916df8b50b2549deb37a28f78033573b06a60b6fc217cf64
    container_name: pulsar
    ports:
      - 6650:6650  # Pulsar broker port
      - 8080:8080  # Pulsar admin web UI
    command: bin/pulsar standalone
