version: '3'
services:
  pulsar:
    image: apachepulsar/pulsar:latest@sha256:9d6cd5cec2992d004b416f9316a8db976d0552f99617a991a72eb31b85683034
    container_name: pulsar
    ports:
      - 6650:6650  # Pulsar broker port
      - 8080:8080  # Pulsar admin web UI
    command: bin/pulsar standalone
