name: Create Badge Coverage

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to test this action
    steps:

      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
            token: ${{ secrets.GH_TOKEN }}

      - name: Prepare environment
        id: coverage
        run: |
          go install github.com/jandelgado/gcov2lcov@latest
          cd example-code-coverage
          go test ./... -coverprofile=coverage.out -covermode=atomic
          echo "current_coverage=$(go tool cover -func coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')" >> $GITHUB_ENV
          # Output values to be used by other steps
          echo "path=${BADGE_PATH}" >> $GITHUB_ENV
        env:
          COVERAGE: ${{ env.current_coverage }}
          BADGE_PATH: .github/badges/code-coverage.svg

      # Create the directory where badges will be saved, if needed
      - name: Create destination directory
        env:
          BADGE_PATH: ${{ env.path }}
        run: mkdir -p "${{ env.path }}%/*"

      # Use the output from the `coverage` step
      - name: Generate the badge SVG image
        uses: emibcn/badge-action@v2.0.2
        id: badge
        with:
          label: 'Code coverage'
          status: ${{ env.current_coverage }}
          color: 'green'
          path: ${{ env.path }}

      - name: Upload badge as artifact
        uses: actions/upload-artifact@v3
        with:
          name: badge
          path: ${{ env.path }}
          if-no-files-found: error

      - name: Push result to git
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore(coverage): updated master coverage [skip ci]'
          file_pattern: ${{ env.path }}