jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: run tests
        run: |
          go test ./example-code-coverage/... -coverprofile=coverage.out

      - name: generate diff
        run: |
          git diff origin/${{ github.base_ref }}...origin/${{ github.head_ref }} > pr.diff

      - name: compute new code coverage
        id: covdiffaction
        uses: panagiotisptr/cov-diff@main
        with:
          path: .
          coverprofile: coverage.out
          diff: pr.diff
          module: github.com/panagiotisptr/cov-diff

      - name: Comment
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            Coverage on new code: ${{ steps.covdiffaction.outputs.covdiff }}%