name: Fetch PR Author and Reviewers

on:
  push:
    branches:
      - main

jobs:
  fetch-pr-details:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Pull Request Info
        id: get-pr-info
        run: |
          # Fetch the PR that triggered the push
          PR_NUMBER=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls" \
            -H "Accept: application/vnd.github.groot-preview+json" | jq -r '.[0].number')
          
          echo "Pull Request Number: $PR_NUMBER"
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

      - name: Get PR Author and Reviews
        id: get-pr-details
        run: |
          # Fetch PR details (to get author)
          PR_DETAILS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER")
          
          PR_AUTHOR=$(echo "$PR_DETAILS" | jq -r '.user.login')
          echo "PR Author: $PR_AUTHOR"
          echo "PR_AUTHOR=$PR_AUTHOR" >> $GITHUB_ENV
          
          # Fetch PR reviews
          REVIEWS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/reviews")
          
          # Extract approved reviewers
          APPROVED=$(echo "$REVIEWS" | jq -r '[.[] | select(.state == "APPROVED") | .user.login] | unique | join(", ")')
          NOT_APPROVED=$(echo "$REVIEWS" | jq -r '[.[] | select(.state != "APPROVED") | .user.login] | unique | join(", ")')
          
          echo "Approved Reviewers: $APPROVED"
          echo "Not Approved Reviewers: $NOT_APPROVED"
          
          # Export to environment variables
          echo "APPROVED=$APPROVED" >> $GITHUB_ENV
          echo "NOT_APPROVED=$NOT_APPROVED" >> $GITHUB_ENV

      - name: Display Results
        run: |
          echo "Pull Request Author: ${{ env.PR_AUTHOR }}"
          echo "Approved Reviewers: ${{ env.APPROVED }}"
          echo "Not Approved Reviewers: ${{ env.NOT_APPROVED }}"