name: Create PR as Specific User

on:
  workflow_dispatch:


jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Make changes to pull request
        run: date +%s > report.txt

      - name: Run the Action
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          target_branch: main
          title: My pull request
          label: enhancement
          template: 'pull_request_template.md