services:
# enable this if you want to use dockerized app
#  golang-app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    networks:
#      - app-network

#  envoy:
#    image: envoyproxy/envoy:v1.27.0
#    volumes:
#      - ./envoy_docker.yaml:/etc/envoy/envoy.yaml
#    ports:
#      - "10000:10000" # Expose Envoy listener port
#      - "9901:9901"   # Expose Envoy admin interface
#    networks:
#      - app-network

  envoy:
    image: envoyproxy/envoy:v1.27.0
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "10000:10000" # Expose Envoy listener port
      - "9901:9901"   # Expose Envoy admin interface
    networks:
      - app-network

networks:
  app-network:
    driver: bridge